version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Project
          command: npm run build

  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: vercel --prod --token $VERCEL_TOKEN

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build